name: test

on:
  push:
    branches: [ "miTest" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Chequear el código desde el repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Especifica la versión de Python que necesitas

      - name: Ejecutar pruebas de distancia
        run: |
          python -m unittest testDistancia.py 

      - name: Ejecutar pruebas de factorial
        run: |
          python -m unittest testFactorial.py  

      - name: Ejecutar pruebas de máximo de lista
        run: |
          python -m unittest testMaximo.py  

      - name: Ejecutar pruebas de primo
        run: |
          python -m unittest testPrimo.py  

      - name: Ejecutar pruebas de temperatura
        run: |
          python -m unittest testTemperatura.py  