name: test

on:
  push:
    branches: [ "miTest" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Chequear el código desde el repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Especifica la versión de Python que necesitas

      - name: Ejecutar pruebas
        run: |
          python -m unittest discover -s . -p "test*.py" 
